#!/usr/bin/env python3
"""
en_fig6_ablation.py
English version of Fig6: Ablation Study
Output: ../output/en_fig6_ablation.pdf
"""
# <<< REAL_DATA_START:ABLATION_DATA
# AUTO-GENERATED by collect_real_data.py at 2026-03-21 03:24:25
ABLATION_DATA = [
  {
    "label": "Dilu-NPU (Full)",
    "peak_npus": 114,
    "svr": 0.37,
    "csc": 63,
    "avg_tput": 27.57,
    "avg_lat_ms": 50.31
  },
  {
    "label": "Dilu-NPU -VS",
    "peak_npus": 114,
    "svr": 0.455,
    "csc": 63,
    "avg_tput": 25.71,
    "avg_lat_ms": 54.44
  },
  {
    "label": "Dilu-NPU -WA",
    "peak_npus": 114,
    "svr": 0.37,
    "csc": 63,
    "avg_tput": 27.57,
    "avg_lat_ms": 50.31
  },
  {
    "label": "Dilu-NPU -RC",
    "peak_npus": 111,
    "svr": 0.405,
    "csc": 59,
    "avg_tput": 25.52,
    "avg_lat_ms": 54.34
  },
  {
    "label": "Dilu-NPU -VS-WA-RC",
    "peak_npus": 111,
    "svr": 0.765,
    "csc": 59,
    "avg_tput": 23.8,
    "avg_lat_ms": 58.81
  }
]
# REAL_DATA_END:ABLATION_DATA >>>

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   '..', 'output', 'en_fig6_ablation.pdf')
plt.rcParams.update({'font.family': 'DejaVu Sans',
                     'axes.unicode_minus': False, 'font.size': 10})

variants = ['Full\nSystem', '-Temporal\n(-VS)', '-Affinity\n(-WA)',
            '-Complement\n(-RC)', 'All-off\n(-VS-WA-RC)']
svr      = [37.0, 45.5, 37.0, 40.5, 76.5]
tput     = [27.6, 25.7, 27.6, 25.5, 23.8]
avg_lat  = [50.3, 54.4, 50.3, 54.3, 66.9]
colors   = ['#E05252', '#F4A460', '#90C3A0', '#DDA0DD', '#B0B0B0']
x = np.arange(len(variants))

fig, axes = plt.subplots(1, 3, figsize=(14, 4.8))
fig.suptitle('Fig.6  Ablation Study: Contribution of Each Component  (N=200 Simulation)',
             fontsize=11, fontweight='bold', y=1.02)

# (A) SVR
ax = axes[0]
bars = ax.bar(x, svr, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, svr):
    ax.text(b.get_x()+b.get_width()/2, v+0.8, f'{v}%',
            ha='center', fontsize=9, fontweight='bold')
for i, v in enumerate(svr[1:], 1):
    delta = v - svr[0]
    if delta > 0:
        ax.annotate(f'+{delta:.1f}pp', xy=(i, v), xytext=(i, v+5),
                    ha='center', fontsize=8, color='red',
                    arrowprops=dict(arrowstyle='->', color='red', lw=1))
ax.set_xticks(x); ax.set_xticklabels(variants, fontsize=8.5)
ax.set_ylabel('SLA Violation Rate SVR (%)')
ax.set_title('(A) SVR  (lower is better)')
ax.set_ylim(0, 98); ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top', 'right']].set_visible(False)

# (B) Throughput
ax = axes[1]
bars = ax.bar(x, tput, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, tput):
    ax.text(b.get_x()+b.get_width()/2, v+0.15, f'{v}',
            ha='center', fontsize=9, fontweight='bold')
for i, v in enumerate(tput[1:], 1):
    delta = v - tput[0]
    ax.text(i, v-2.2, f'{delta:+.1f}', ha='center', fontsize=8,
            color='red' if delta < 0 else 'green', fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(variants, fontsize=8.5)
ax.set_ylabel('Throughput (req/s)')
ax.set_title('(B) Throughput  (higher is better)')
ax.set_ylim(18, 32); ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top', 'right']].set_visible(False)

# (C) Mean latency
ax = axes[2]
bars = ax.bar(x, avg_lat, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, avg_lat):
    ax.text(b.get_x()+b.get_width()/2, v+0.4, f'{v}ms',
            ha='center', fontsize=9, fontweight='bold')
ax.axhline(50, color='red', ls='--', lw=1.5, alpha=.7, label='SLO = 50ms')
ax.set_xticks(x); ax.set_xticklabels(variants, fontsize=8.5)
ax.set_ylabel('Mean Latency (ms)')
ax.set_title('(C) Mean Latency  (lower is better)')
ax.set_ylim(40, 82); ax.legend(fontsize=8.5)
ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig(OUT, dpi=200, bbox_inches='tight')
print(f'Saved: {OUT}')
plt.close()
