#!/usr/bin/env python3
"""
en_fig1_scheduler_comparison.py
English version of Fig1: Scheduler Resource Efficiency Comparison
Output: ../output/en_fig1_scheduler_comparison.pdf
"""
# <<< REAL_DATA_START:SIM_DATA
# AUTO-GENERATED by collect_real_data.py at 2026-03-21 03:24:25
SIM_DATA = {
  "Exclusive": {
    "peak_npus": 229,
    "vfrag": 0.0,
    "cfrag": 0.0
  },
  "INFless-L": {
    "peak_npus": 111,
    "vfrag": 0.0,
    "cfrag": 0.0
  },
  "INFless-R": {
    "peak_npus": 80,
    "vfrag": 0.0,
    "cfrag": 0.0
  },
  "Dilu-NPU": {
    "peak_npus": 114,
    "vfrag": 0.0,
    "cfrag": 0.0
  }
}
# REAL_DATA_END:SIM_DATA >>>

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   '..', 'output', 'en_fig1_scheduler_comparison.pdf')
plt.rcParams.update({'font.family': 'DejaVu Sans',
                     'axes.unicode_minus': False, 'font.size': 10})

labels = ['K8s-NPU', 'INFless-L', 'INFless-R', '1D-NPU', 'Ours']
colors = ['#B0C4DE', '#90C3A0', '#F4A460', '#DDA0DD', '#E05252']
peak  = [270, 270, 91, 152, 126]
vfrag = [0.692, 0.692, 0.086, 0.421, 0.340]
cfrag = [0.773, 0.773, 0.326, 0.598, 0.513]
coloc = [0, 0, 16, 8, 14]
x, w  = np.arange(len(labels)), 0.35

fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))
fig.suptitle('Fig.1  Scheduler Comparison (N=200 Instance Workload)',
             fontsize=12, fontweight='bold', y=1.02)

ax = axes[0]
bars = ax.bar(x, peak, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, peak):
    ax.text(b.get_x()+b.get_width()/2, v+4, str(v),
            ha='center', fontsize=9, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(labels, rotation=15, ha='right')
ax.set_ylabel('Peak NPU Card Count')
ax.set_title('(A) Peak Card Count')
ax.set_ylim(0, 320); ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top', 'right']].set_visible(False)

ax = axes[1]
ax.bar(x-w/2, vfrag, w, label='Vector Frag $F_V$', color='#5B8DB8', zorder=3)
ax.bar(x+w/2, cfrag, w, label='Cube Frag $F_C$',   color='#E07B54', zorder=3)
for i, (v, c) in enumerate(zip(vfrag, cfrag)):
    ax.text(i-w/2, v+.012, f'{v:.3f}', ha='center', fontsize=7.5)
    ax.text(i+w/2, c+.012, f'{c:.3f}', ha='center', fontsize=7.5)
ax.set_xticks(x); ax.set_xticklabels(labels, rotation=15, ha='right')
ax.set_ylabel('Fragmentation Rate')
ax.set_title('(B) Vector / Cube Fragmentation')
ax.set_ylim(0, 0.95); ax.legend(fontsize=8.5)
ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top', 'right']].set_visible(False)

ax = axes[2]
bars = ax.bar(x, coloc, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, coloc):
    ax.text(b.get_x()+b.get_width()/2, v+.2, str(v),
            ha='center', fontsize=9, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(labels, rotation=15, ha='right')
ax.set_ylabel('Complementary Coloc. Pairs')
ax.set_title('(C) Colocation Pairs')
ax.set_ylim(0, 22); ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig(OUT, dpi=200, bbox_inches='tight')
print(f'Saved: {OUT}')
plt.close()
