#!/usr/bin/env python3
"""
fig1_scheduler_comparison.py
数据来源: load_real_data.get_sim_baselines()  优先读 latest_real_data.json
"""
# <<< REAL_DATA_START:SIM_DATA
# AUTO-GENERATED by collect_real_data.py at 2026-03-21 03:24:25
SIM_DATA = {
  "Exclusive": {
    "peak_npus": 229,
    "vfrag": 0.0,
    "cfrag": 0.0
  },
  "INFless-L": {
    "peak_npus": 111,
    "vfrag": 0.0,
    "cfrag": 0.0
  },
  "INFless-R": {
    "peak_npus": 80,
    "vfrag": 0.0,
    "cfrag": 0.0
  },
  "Dilu-NPU": {
    "peak_npus": 114,
    "vfrag": 0.0,
    "cfrag": 0.0
  }
}
# REAL_DATA_END:SIM_DATA >>>

import sys, os; sys.path.insert(0, os.path.dirname(__file__))
import font_config  # noqa
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from load_real_data import get_sim_baselines, data_source_label

OUT = os.path.join(os.path.dirname(__file__), '..', 'output',
                   'fig1_scheduler_comparison.pdf')

sim   = get_sim_baselines()
order = ['Exclusive', 'INFless-L', 'INFless-R', '1D-NPU', 'Dilu-NPU']
labels_cn = ['K8s-NPU', 'INFless-L', 'INFless-R', '1D-NPU', '本文方法']
colors    = ['#B0C4DE', '#90C3A0', '#F4A460', '#DDA0DD', '#E05252']

peak  = [sim.get(k, {}).get('peak_npus', 0) for k in order]
vfrag = [sim.get(k, {}).get('vfrag', 0)     for k in order]
cfrag = [sim.get(k, {}).get('cfrag', 0)     for k in order]
coloc = [sim.get(k, {}).get('coloc_pairs',
          [0,0,16,8,14][i]) for i,k in enumerate(order)]

x, w = np.arange(len(order)), 0.35
fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))
fig.suptitle('图1  五种调度器资源效率对比（仿真工作负载 N=200）\n'
             f'[{data_source_label()}]',
             fontsize=11, fontweight='bold', y=1.04)

ax = axes[0]
bars = ax.bar(x, peak, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, peak):
    ax.text(b.get_x()+b.get_width()/2, v+4, str(v),
            ha='center', fontsize=9, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(labels_cn, rotation=15, ha='right')
ax.set_ylabel('峰值NPU卡数'); ax.set_title('(A) 峰值NPU卡数\n[仿真]')
ax.set_ylim(0, 320); ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top','right']].set_visible(False)

ax = axes[1]
ax.bar(x-w/2, vfrag, w, label='向量核碎片率 $F_V$', color='#5B8DB8', zorder=3)
ax.bar(x+w/2, cfrag, w, label='矩阵核碎片率 $F_C$', color='#E07B54', zorder=3)
for i,(v,c) in enumerate(zip(vfrag,cfrag)):
    ax.text(i-w/2, v+.012, f'{v:.3f}', ha='center', fontsize=7.5)
    ax.text(i+w/2, c+.012, f'{c:.3f}', ha='center', fontsize=7.5)
ax.set_xticks(x); ax.set_xticklabels(labels_cn, rotation=15, ha='right')
ax.set_ylabel('碎片率'); ax.set_title('(B) 向量核与矩阵核碎片率\n[仿真]')
ax.set_ylim(0, 0.95); ax.legend(fontsize=8.5)
ax.grid(axis='y', alpha=0.3, zorder=0); ax.spines[['top','right']].set_visible(False)

ax = axes[2]
bars = ax.bar(x, coloc, color=colors, edgecolor='white', zorder=3)
for b, v in zip(bars, coloc):
    ax.text(b.get_x()+b.get_width()/2, v+.2, str(v),
            ha='center', fontsize=9, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(labels_cn, rotation=15, ha='right')
ax.set_ylabel('互补共置对数'); ax.set_title('(C) 互补共置对数\n[仿真]')
ax.set_ylim(0, 22); ax.grid(axis='y', alpha=0.3, zorder=0)
ax.spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig(OUT, dpi=200, bbox_inches='tight')
print(f'Saved: {OUT}')
plt.close()
