#!/usr/bin/env python3
"""
fig6_ablation.py
数据来源: load_real_data.get_ablation()  优先读 latest_real_data.json
"""
# <<< REAL_DATA_START:ABLATION_DATA
# AUTO-GENERATED by collect_real_data.py at 2026-03-21 03:24:25
ABLATION_DATA = [
  {
    "label": "Dilu-NPU (Full)",
    "peak_npus": 114,
    "svr": 0.37,
    "csc": 63,
    "avg_tput": 27.57,
    "avg_lat_ms": 50.31
  },
  {
    "label": "Dilu-NPU -VS",
    "peak_npus": 114,
    "svr": 0.455,
    "csc": 63,
    "avg_tput": 25.71,
    "avg_lat_ms": 54.44
  },
  {
    "label": "Dilu-NPU -WA",
    "peak_npus": 114,
    "svr": 0.37,
    "csc": 63,
    "avg_tput": 27.57,
    "avg_lat_ms": 50.31
  },
  {
    "label": "Dilu-NPU -RC",
    "peak_npus": 111,
    "svr": 0.405,
    "csc": 59,
    "avg_tput": 25.52,
    "avg_lat_ms": 54.34
  },
  {
    "label": "Dilu-NPU -VS-WA-RC",
    "peak_npus": 111,
    "svr": 0.765,
    "csc": 59,
    "avg_tput": 23.8,
    "avg_lat_ms": 58.81
  }
]
# REAL_DATA_END:ABLATION_DATA >>>

import sys, os; sys.path.insert(0, os.path.dirname(__file__))
import font_config  # noqa
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from load_real_data import get_ablation, data_source_label

OUT = os.path.join(os.path.dirname(__file__), '..', 'output',
                   'fig6_ablation.pdf')

ablation = get_ablation()
LABEL_CN = {
    'Dilu-NPU (Full)':     '完整方法',
    'Dilu-NPU -VS':        '-时序感知\n(-VS)',
    'Dilu-NPU -WA':        '-亲和调度\n(-WA)',
    'Dilu-NPU -RC':        '-互补调度\n(-RC)',
    'Dilu-NPU -VS-WA-RC':  '全关\n(-VS-WA-RC)',
}
labels  = [LABEL_CN.get(r.get('label',''), r.get('label','')) for r in ablation]
svr     = [r.get('svr', 0)*100  for r in ablation]
tput    = [r.get('avg_tput', 0) for r in ablation]
avg_lat = [r.get('avg_lat_ms',0) for r in ablation]
colors  = ['#E05252','#F4A460','#90C3A0','#DDA0DD','#B0B0B0']
x = np.arange(len(labels))

fig, axes = plt.subplots(1, 3, figsize=(14, 4.8))
fig.suptitle('图6  消融实验：各组件独立贡献（仿真工作负载 N=200）\n'
             '⚠ -WA在纯推理场景无增量收益，需混合训练/推理负载验证\n'
             f'[{data_source_label()}]',
             fontsize=10, fontweight='bold', y=1.06)

# 子图A: SVR
ax = axes[0]
bars = ax.bar(x, svr, color=colors[:len(x)], edgecolor='white', zorder=3)
for b, v in zip(bars, svr):
    ax.text(b.get_x()+b.get_width()/2, v+0.8,
            f'{v:.1f}%', ha='center', fontsize=9, fontweight='bold')
if len(svr) > 1:
    for i, v in enumerate(svr[1:], 1):
        delta = v - svr[0]
        if delta > 0.5:
            ax.annotate(f'+{delta:.1f}pp',
                        xy=(i, v), xytext=(i, v+5),
                        ha='center', fontsize=8, color='red',
                        arrowprops=dict(arrowstyle='->', color='red', lw=1))
ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
ax.set_ylabel('SLA违约率 SVR (%)')
ax.set_title('(A) SLA违约率 [仿真]\n（越低越好）')
ax.set_ylim(0, max(svr)*1.35 + 5)
ax.grid(axis='y', alpha=.3, zorder=0)
ax.spines[['top','right']].set_visible(False)

# 子图B: 吞吐量
ax = axes[1]
bars = ax.bar(x, tput, color=colors[:len(x)], edgecolor='white', zorder=3)
for b, v in zip(bars, tput):
    ax.text(b.get_x()+b.get_width()/2, v+0.2,
            f'{v:.1f}', ha='center', fontsize=9, fontweight='bold')
if len(tput) > 1:
    for i, v in enumerate(tput[1:], 1):
        delta = v - tput[0]
        ax.text(i, v-2.5, f'{delta:+.1f}', ha='center', fontsize=8,
                color='red' if delta < 0 else 'green', fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
ax.set_ylabel('吞吐量 (req/s)')
ax.set_title('(B) 吞吐量 [仿真]\n（越高越好）')
ax.set_ylim(max(0, min(tput)-5), max(tput)+5)
ax.grid(axis='y', alpha=.3, zorder=0)
ax.spines[['top','right']].set_visible(False)

# 子图C: 均值延迟
ax = axes[2]
bars = ax.bar(x, avg_lat, color=colors[:len(x)], edgecolor='white', zorder=3)
for b, v in zip(bars, avg_lat):
    ax.text(b.get_x()+b.get_width()/2, v+0.4,
            f'{v:.1f}ms', ha='center', fontsize=9, fontweight='bold')
ax.axhline(50, color='red', ls='--', lw=1.5, alpha=.7, label='SLO=50ms')
ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
ax.set_ylabel('均值延迟 (ms)')
ax.set_title('(C) 均值延迟 [仿真]\n（越低越好）')
ax.set_ylim(max(0, min(avg_lat)-8), max(avg_lat)+12)
ax.legend(fontsize=8.5)
ax.grid(axis='y', alpha=.3, zorder=0)
ax.spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig(OUT, dpi=200, bbox_inches='tight')
print(f'Saved: {OUT}')
plt.close()
